### ISSUE TITLE
Handling NA data

### ISSUE THREAD

**Issue by matthewhlaw** [StoreyLab/gcat#1]
Sorry this is not the right way to raise issues - I haven't used github before. 

1) I am trying to use GCAT and when I applies lfa to my genotype data it reports 
# Error in if ((S < SVTol) && (j == 1)) stop("error: starting vector near the null space") :  missing value where TRUE/FALSE needed

Which I presume to be due to the missingness in the data (genotype data is cleaned in PLINK to geno and mind 0.03). However in your paper you report cleaning the North Finland Cohort data at 1% missingness. Can the gcat method handle missingness in PLINK genotype data, and if so how should the missingness be coded? 

2) The GCAT method appears to be very memory intensive for even small sets (1000 people, 700K SNPs) - do you know roughly how it scales in terms of RAM needed for N indivduals and M SNPs? 

Thanks

Matthew

**Comment by whao89** [comment]
Hi Matthew,

I've pushed the code used in the paper for NAs as part of the package. The functions should check for the presence of NAs appropriately. The package code has become a bit more sophisticated than the code for the paper so I will be making some changes in the coming weeks to improve NA handling, though the function prototypes, etc. will not change.

The truncated SVD trades off memory for time---if memory is more valuable to you, then the override option in the `lfa` function will cause the method to use a typical SVD function, which is much slower but has a smaller memory footprint.

I have been informed there are a few other implementations of these truncated SVD approaches, so improvements may come there soon as well.

Thanks
Wei

**Comment by matthewhlaw** [comment]
Thanks Wei - I have installed the new version and it is handling NAs now.

Matthew
